# Module: sql
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.10/metricbeat-module-sql.html

#There are hardcoded passwords in here. This is purely a test. 
#For any production workloads, a secrets vault should be used so that the password can be injected at run time.

- module: sql
  metricsets:
    - query
  period: 10s
  hosts: ["sqlserver://kibana:kibana0161@localhost"]

  driver: "mssql"
  sql_query: "SELECT   cpu_sql = record.value('(./Record/SchedulerMonitorEvent/SystemHealth/ProcessUtilization)[1]', 'int')
FROM (
         SELECT TOP 1 CONVERT(XML, record) AS record
         FROM sys.dm_os_ring_buffers
         WHERE ring_buffer_type = N'RING_BUFFER_SCHEDULER_MONITOR'
         AND record LIKE '% %'
		 ORDER BY TIMESTAMP DESC
) as cpu_usage"
  sql_response_format: table

- module: sql
  metricsets:
    - query
  period: 10s
  hosts: ["sqlserver://kibana:kibana0161@localhost"]

  driver: "mssql"
  sql_query: "
SELECT cpu_idle = record.value('(./Record/SchedulerMonitorEvent/SystemHealth/SystemIdle)[1]', 'int')
FROM (
         SELECT TOP 1 CONVERT(XML, record) AS record
         FROM sys.dm_os_ring_buffers
         WHERE ring_buffer_type = N'RING_BUFFER_SCHEDULER_MONITOR'
         AND record LIKE '% %'
		 ORDER BY TIMESTAMP DESC
) as cpu_usage"
  sql_response_format: table